### PR TITLE
Add and fix compiler warnings

### PR DESCRIPTION
**Pull request by ChrisThrasher**
Eventually `-Wconversion` and `-Wsign-conversion` should be added as well. Warnings-as-errors are enabled and CI will be checking that so introducing more warnings in the future shouldn't be a problem.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
I removed some unused parameters. Feel free to add them back if you choose to start using them but for the time being, it's best to keep the API as minimal as required. I also added a missing virtual destructor to fix a potential resource leak.

**Comment by ChrisThrasher** [comment]
Windows is warning about more lossy conversions but without a Windows machine to use it's a bit tedious to fix.

**Comment by CosminPerRam** [comment]
Thanks for the pull, I'll tackle on the windows conversions.

**Comment by CosminPerRam** [comment]
I have decided to just disable the implicit conversions warnings as I think they dont pose a problem and i dont want to clutter a lot of the code with explicit stuff

**Review by CosminPerRam — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
I disagree but that's your call to make. Ideally you'd restructure the code to minimize the number of lossy conversions required because all those lossy conversions are more places for important data to potentially get lost.

**Comment by CosminPerRam** [comment]
Fair enough argument, updated.

**Comment by CosminPerRam** [comment]
Had to do another commit because some warnings showed up only after i cleaned the build.

**Pull request merged**
